# Generated by Django 5.2.7 on 2025-11-28 14:15

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Хеш файла"
                    ),
                ),
                ("file", models.ImageField(upload_to="avatars/unique/", verbose_name="Файл")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Количество использований"),
                ),
            ],
            options={
                "verbose_name": "Файл аватара",
                "verbose_name_plural": "Файлы аватаров",
                "ordering": ["-created_at"],
            },
        ),
        # Добавляем новое поле как ForeignKey (nullable, чтобы не потерять данные)
        migrations.AddField(
            model_name="profile",
            name="avatar_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.avatarfile",
                verbose_name="Аватар (новый)",
            ),
        ),
        # Удаляем старое поле avatar
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        # Переименовываем avatar_new в avatar
        migrations.RenameField(
            model_name="profile",
            old_name="avatar_new",
            new_name="avatar",
        ),
    ]
