# Generated by Django 5.2.7 on 2025-12-01 12:05

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_avatarfile_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.avatarfile",
                verbose_name="Аватар",
            ),
        ),
    ]
