"""
Mock данные для тестирования - реалистичные примеры как на Stack Overflow
"""

# Вопросы для списка новых вопросов
NEW_QUESTIONS = [
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
    {
        'id': 1,
        'title': 'How to implement JWT authentication in Django REST Framework?',
        'text': 'I\'m trying to implement JWT authentication in my Django REST Framework application. I\'ve installed djangorestframework-simplejwt but I\'m having trouble configuring it properly...',
        'author': 'python_dev',
        'rating': 45,
        'answers_count': 12,
        'tags': ['python', 'django', 'jwt', 'rest-api'],
    },
    {
        'id': 2,
        'title': 'React hooks: How to properly use useEffect with dependencies?',
        'text': 'I\'m confused about when to include dependencies in the useEffect dependency array. Sometimes my component re-renders unnecessarily, other times it doesn\'t update when it should...',
        'author': 'react_master',
        'rating': 32,
        'answers_count': 8,
        'tags': ['javascript', 'react', 'hooks', 'useeffect'],
    },
    {
        'id': 3,
        'title': 'Docker: Best practices for multi-stage builds',
        'text': 'I\'m trying to optimize my Docker images and heard about multi-stage builds. What are the best practices for using them in production environments?',
        'author': 'devops_guru',
        'rating': 28,
        'answers_count': 15,
        'tags': ['docker', 'devops', 'containers'],
    },
    {
        'id': 4,
        'title': 'MySQL vs PostgreSQL: Which to choose for a new project?',
        'text': 'Starting a new web application and need to decide on the database. What are the key differences between MySQL and PostgreSQL in 2025?',
        'author': 'database_expert',
        'rating': 67,
        'answers_count': 23,
        'tags': ['mysql', 'postgresql', 'database', 'comparison'],
    },
    {
        'id': 5,
        'title': 'Git merge conflicts: How to resolve them efficiently?',
        'text': 'I often encounter merge conflicts when working in a team. What are the best strategies and tools for resolving them quickly and correctly?',
        'author': 'git_expert',
        'rating': 52,
        'answers_count': 18,
        'tags': ['git', 'version-control', 'merge'],
    },
    {
        'id': 6,
        'title': 'TypeScript: Understanding type inference and when to use explicit types',
        'text': 'When should I rely on TypeScript\'s type inference vs explicitly declaring types? I\'m new to TypeScript and want to write maintainable code.',
        'author': 'ts_learner',
        'rating': 19,
        'answers_count': 7,
        'tags': ['typescript', 'javascript', 'type-safety'],
    },
    {
        'id': 7,
        'title': 'How to optimize database queries in Django ORM?',
        'text': 'My Django application is slow due to N+1 queries. What are the best practices for using select_related and prefetch_related to optimize database access?',
        'author': 'django_master',
        'rating': 89,
        'answers_count': 34,
        'tags': ['python', 'django', 'orm', 'database', 'performance'],
    },
    {
        'id': 8,
        'title': 'Kubernetes: Setting up a local development environment',
        'text': 'I want to learn Kubernetes by running it locally on my machine. What tools and setup do you recommend for local development?',
        'author': 'k8s_newbie',
        'rating': 24,
        'answers_count': 11,
        'tags': ['kubernetes', 'devops', 'containers', 'local-dev'],
    },
    {
        'id': 9,
        'title': 'Async/await in Python: When to use and best practices',
        'text': 'I\'m working with I/O-bound operations in Python. When should I use asyncio vs multithreading? What are the common pitfalls with async/await?',
        'author': 'python_dev',
        'rating': 41,
        'answers_count': 16,
        'tags': ['python', 'async', 'asyncio', 'performance'],
    },
    {
        'id': 10,
        'title': 'Microservices architecture: How to handle distributed transactions?',
        'text': 'We\'re migrating to microservices but struggling with maintaining data consistency across services. What patterns and approaches would you recommend?',
        'author': 'architect_pro',
        'rating': 76,
        'answers_count': 28,
        'tags': ['microservices', 'architecture', 'distributed-systems'],
    },
    {
        'id': 11,
        'title': 'CSS Grid vs Flexbox: When to use each?',
        'text': 'I\'m learning modern CSS layout techniques. Can someone explain the main differences and when each approach is more appropriate?',
        'author': 'frontend_dev',
        'rating': 38,
        'answers_count': 14,
        'tags': ['css', 'flexbox', 'grid', 'layout'],
    },
    {
        'id': 12,
        'title': 'How to implement real-time updates with WebSockets in Django?',
        'text': 'I need to add real-time notifications to my Django application. Should I use Django Channels, WebSockets, or Server-Sent Events?',
        'author': 'django_real_time',
        'rating': 43,
        'answers_count': 19,
        'tags': ['python', 'django', 'websockets', 'channels', 'real-time'],
    },
    {
        'id': 13,
        'title': 'Vue.js 3 Composition API: Migration guide from Options API',
        'text': 'We\'re planning to migrate our Vue 2 application to Vue 3 with Composition API. What are the key differences and migration considerations?',
        'author': 'vue_migrator',
        'rating': 35,
        'answers_count': 13,
        'tags': ['vuejs', 'javascript', 'composition-api'],
    },
    {
        'id': 14,
        'title': 'Redis: Best practices for caching strategies',
        'text': 'I\'m implementing caching in my application using Redis. What caching patterns (cache-aside, write-through, etc.) work best in different scenarios?',
        'author': 'redis_user',
        'rating': 49,
        'answers_count': 21,
        'tags': ['redis', 'caching', 'performance'],
    },
    {
        'id': 15,
        'title': 'How to handle file uploads securely in web applications?',
        'text': 'I need to allow users to upload files in my web application. What security considerations should I keep in mind (file type validation, size limits, etc.)?',
        'author': 'security_aware',
        'rating': 61,
        'answers_count': 25,
        'tags': ['security', 'file-upload', 'validation'],
    },
]

# Популярные вопросы (с высоким рейтингом)
HOT_QUESTIONS = [
    {
        'id': 101,
        'title': 'The definitive guide to Git branching strategy in 2025',
        'text': 'After years of experience with different Git workflows, here\'s a comprehensive guide to choosing and implementing the right branching strategy for your team...',
        'author': 'git_guru',
        'rating': 1247,
        'answers_count': 156,
        'tags': ['git', 'version-control', 'best-practices'],
    },
    {
        'id': 102,
        'title': 'Django best practices for large-scale applications',
        'text': 'I\'ve been building Django applications for 10+ years. Here are the lessons learned about structuring large Django projects, managing models, and optimizing queries...',
        'author': 'django_veteran',
        'rating': 892,
        'answers_count': 134,
        'tags': ['python', 'django', 'architecture', 'scalability'],
    },
    {
        'id': 103,
        'title': 'Complete guide to React performance optimization',
        'text': 'From memoization to code splitting: everything you need to know about making React applications performant and smooth...',
        'author': 'react_perf_expert',
        'rating': 765,
        'answers_count': 98,
        'tags': ['react', 'javascript', 'performance', 'optimization'],
    },
    {
        'id': 104,
        'title': 'Node.js async/await pitfalls and how to avoid them',
        'text': 'After debugging countless async issues in Node.js, here are the most common mistakes developers make and how to write bulletproof async code...',
        'author': 'nodejs_dev',
        'rating': 634,
        'answers_count': 87,
        'tags': ['nodejs', 'javascript', 'async', 'error-handling'],
    },
    {
        'id': 105,
        'title': 'PostgreSQL vs MySQL: Deep dive comparison 2025',
        'text': 'Updated comparison of two most popular open-source databases with real-world benchmarks and use case recommendations...',
        'author': 'db_analyst',
        'rating': 542,
        'answers_count': 112,
        'tags': ['postgresql', 'mysql', 'database', 'comparison'],
    },
]

# Ответы на вопрос
SAMPLE_ANSWERS = [
    {
        'id': 1,
        'text': 'For Django REST Framework JWT authentication, you need to install `djangorestframework-simplejwt` and configure it in your settings. Here\'s the typical setup:\n\n```python\nINSTALLED_APPS = [\n    # ...\n    \'rest_framework_simplejwt\',\n]\n\nREST_FRAMEWORK = {\n    \'DEFAULT_AUTHENTICATION_CLASSES\': (\n        \'rest_framework_simplejwt.authentication.JWTAuthentication\',\n    ),\n}\n```',
        'author': 'jwt_expert',
        'rating': 15,
        'is_correct': True,
    },
    {
        'id': 2,
        'text': 'Make sure to also configure the token settings in your settings.py. You\'ll need to set SIMPLE_JWT configuration dictionary with proper token lifetimes.',
        'author': 'django_helper',
        'rating': 8,
        'is_correct': False,
    },
    {
        'id': 3,
        'text': 'Don\'t forget that you also need to configure URL routing for token refresh in your urls.py. Also, remember to use HTTPS in production for security.',
        'author': 'security_advisor',
        'rating': 5,
        'is_correct': False,
    },
]

# Все доступные теги
ALL_TAGS = [
    'python', 'django', 'flask', 'fastapi', 'pytest',
    'javascript', 'react', 'vue', 'angular', 'typescript',
    'nodejs', 'express', 'nextjs',
    'java', 'spring-boot', 'hibernate',
    'csharp', 'dotnet', 'aspnet',
    'go', 'golang', 'gin',
    'rust', 'cargo',
    'php', 'laravel', 'symfony',
    'ruby', 'rails',
    'html', 'css', 'sass', 'scss', 'bootstrap', 'tailwindcss',
    'docker', 'kubernetes', 'jenkins', 'ci-cd',
    'aws', 'azure', 'gcp', 'terraform',
    'mysql', 'postgresql', 'mongodb', 'redis', 'elasticsearch',
    'git', 'github', 'gitlab', 'bitbucket',
    'linux', 'bash', 'shell-scripting',
    'rest-api', 'graphql', 'microservices',
    'machine-learning', 'tensorflow', 'pytorch',
    'security', 'oauth', 'jwt', 'encryption',
    'testing', 'unit-testing', 'integration-testing',
    'agile', 'scrum', 'devops',
]

